### PR TITLE
Configure `pg_hba.conf`

### PR DESCRIPTION
**Pull request by shivaraj-bh**
[Merges to #3]

### CODE REVIEW

**Review by srid — CHANGES_REQUESTED** [review]
This PR is done right? Once the flake input points back to `main` branch, we can merge this.

**Comment by srid** [comment]
I added Jenkins CI to `nixify` branch. If you rebase, Jenkins will build this PR too.

**Comment by shivaraj-bh** [comment]
`passetto-service` not working on MacOS is because of https://github.com/juspay/passetto/issues/2

> This PR is done right? Once the flake input points back to main branch, we can merge this.

Yes, we can merge this!

**Comment by shivaraj-bh** [comment]
> passetto-service not working on MacOS is because of https://github.com/juspay/passetto/issues/2


Works on `x86_64-darwin` though, so workaround for now is to use: `nix run --option system x86_64-darwin`

**Pull request merged**
